export type ColinkRequest = {
  sex?: string
  firstname: string
  lastname: string
  age?: number
  cid?: string
  passport?: string
  contact_number: string
  district: string
  province: string
  inspected_location?: string
  inspected_location_type?: string
  inspected_location_owner?: string
  swab_datetime?: Date
  result_ack_datetime?: Date
  bed_waiting_days?: number
  cd_source?: string
  weight?: number
  high?: number
  bmi?: number
  cl_source?: string
  screening_result?: string
  latest_symptom?: string
  latest_follow_datetime?: Date
  status?: string
  transfered_to?: string
  hospital_admitted?: string
  hospital_admitted_datetime?: Date
  note?: string
  age_month?: number
  transfer_method?: string
  address?: string
  subdistrict_code?: string
  district_code?: string
  province_code?: string
  nationality?: string
  address_zone?: string
  test_type?: string
  hospital_admitted_other?: string
  favipiravir_receive_date?: Date
  risk_score?: number
  daily_activity?: string
  pregnancy_week?: number
  favipiravir_by?: string
  treatment_right?: string
}
